//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElderlyCare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblElderPerson
    {
        public int ElderPersonId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public string Contactno { get; set; }
        public string DoctorName { get; set; }
        public string DoctorContactno { get; set; }
        public string HospitalName { get; set; }
        public string HospitalContactno { get; set; }
        public string CareTaker { get; set; }
    }
}
