//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElderlyCare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReminder
    {
        public int ReminderId { get; set; }
        public string ReminderText { get; set; }
        public string Description { get; set; }
        public Nullable<int> ElderPersonId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    }
}
